// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:
// --------------- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... ---------------
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
// find the sum of the even-valued terms.

function evenFiboNum(n) {
  var prev = 0;
  var current = 1;
  var sum = 0;

  while (current <= n) {
    // find even numbers  
    if (current % 2 == 0) {
      // if it is an even number, add into sum
      sum += current;
    }
    
    // current becomes prev
    current += prev;
    // new prev becomes current - prev
    prev = current - prev;
  }
  
  return sum;
}

console.log(evenFiboNum(4000000));